name: rls
channels:
  - http://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - http://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - openssl=1.1.1h=he774522_0
  - pip=20.2.4=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - setuptools=50.3.1=py38haa95532_1
  - sqlite=3.33.0=h2a8f88b_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - cachetools==4.1.1
    - chardet==3.0.4
    - cloudpickle==1.2.2
    - decorator==4.4.2
    - dm-tree==0.1.5
    - docopt==0.6.2
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - gym==0.15.3
    - h5py==2.10.0
    - idna==2.10
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - numpy==1.19.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.11
    - pyyaml==5.3.1
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.4
    - six==1.15.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - tqdm==4.52.0
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - wrapt==1.12.1
